# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

plugins:
  - jekyll-polyglot

version: 0.1
markdown: kramdown
permalink: pretty
exclude: ["README.*", "LICENSE.txt"]
sass:
  style: expanded
  sourcemap: never

languages:
  - en
  - ru
  - de
  - es
default_lang: en
exclude_from_localization:
  - images/*
  - README*
  - LICENSE.txt
  - css/*
parallel_localization: true
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "•"

# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
#name: Synergenex
#subtitle:

# Title attribute of HTML Page, uses 'name' from above if empty
title: Synergenex Links

meta_theme_color: |
  #db242b

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
  keywords: Synergenex, links, media, mirror
  crawl: index,follow

# website address when deployed, also given as canonical link
url: https://links.synergenex.info/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: ""

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
  account: ""
  cookieconsent: true
  anonymizeip: true

# Plausible.io Analytics (alternative to Google Analytics that does not need cookies -> no cookie consent required)
# A config setting is required in plausible to enable tracking of the outbound links. Details described here:
# https://plausible.io/docs/outbound-link-click-tracking
# Leave empty (just "plausible:" with subitems commented out) to disable.
#plausible:
plausible:
  domain: ""

# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "images/logo.svg"
#avatar: "images/jonathan_doe.jpg"
# Enable link for the avatar
avatar_link_enabled: true

# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - web:
      name: Latest mirror
      show: true
      href: https://a.synergenex.com
      icon: fas fa-globe
  - telegram:
      name: Telegram channel
      show: true
      href: https://t.me/synergenex
      icon: fab fa-telegram-plane
  - facebook:
      name: Facebook
      show: false
      href: https://facebook.com/YOUR_FB_USERNAME
      icon: fab fa-facebook
  - vkontakte:
      name: ВКонтакте
      show: false
      href: https://vk.com/YOUR_VK_USERNAME
      icon: fab fa-vk
  - instagram:
      name: Instagram
      show: true
      href: https://instagram.com/synergenex_rus
      icon: fab fa-instagram
  - email:
      name: Email
      show: true
      href: mailto:info@synergenex.com
      icon: fas fa-envelope

# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:

#EOF

forums_enabled: true
forums:
  - anabolicshops:
      name: AnabolicShops
      href: https://bp.anabolicshops.me/threads/12126/page-999999999
      icon: images/forums/anabolicshops.png
  - do4a:
      name: Do4a
      href: https://ax.do4a.me/threads/synergenex-—-откройте-нового-себя.35185/page-999999999
      icon: images/forums/do4a.png
