lang_name: Deutsche
title: Synergenex Links
extra_html: |
  Alle relevanten Links zu Synergenex® Ressourcen an einem Ort: <i class="fas fa-globe fa-fw"></i>&nbsp;Website, <i class="fas fa-envelope fa-fw"></i>&nbsp;E-Mail und Themen in spezialisierten Foren.
no_translation:
  Sorry, this page is not available in this language.
go_to_thread:
  Gehe zu Forenthread