lang_name: English
title: Synergenex Links
robots:
  description: Synergenex – Canadian provider of products enhancing sport results. Products, news, authenticity check, contacts.
extra_html: |
  All relevant links to Synergenex® resources in one place: <i class="fas fa-globe fa-fw"></i>&nbsp;website, <i class="fab fa-telegram-plane fa-fw"></i>&nbsp;Telegram, <i class="fas fa-envelope fa-fw"></i>&nbsp;email and topics on specialized forums.
no_translation:
  Sorry, this page is not available in this language.
go_to_thread:
  Go to Forum Thread
copyright:
  © 2017–2024 Synergenex®

links:
  - web: 
      name: Latest mirror
  - telegram: 
      name: Telegram
  - instagram: 
      name: Instagram
  - email: 
      name: Email