lang_name: Русский
title: Synergenex – Ссылки
robots:
  description: Synergenex — канадский поставщик продуктов, повышающих спортивные результаты. Продукты, новости, проверка подлинности, контакты.
extra_html: |-
  Все актуальные ссылки на ресурсы Synergenex® в одном месте: <i class="fas fa-globe fa-fw"></i>&nbsp;сайт, <i class="fab fa-telegram-plane fa-fw"></i>&nbsp;Telegram, <i class="fas fa-envelope fa-fw"></i>&nbsp;почта и темы на специализированных форумах.
no_translation:
  Извините, но эта страница недоступна на этом языке.
go_to_thread:
  Перейти в ветку форума

links:
  - web:
      name: Актуальное зеркало
  - telegram:
      name: Телеграм-чат
  - instagram: 
      name: Instagram
  - email: 
      name: Эл. почта
